### PR TITLE
Extend the component API

### PR DESCRIPTION
**Pull request by danilvalov**
- add the `onBeginSelection` prop;
- add the `onEndSelection` prop;
- add the `selectingClassName` prop;
- update the `onSelection` callback logic (remove the `selectOnMouseMove` prop).

### CODE REVIEW

**Comment by danilvalov** [comment]
Issue: #48

**Comment by ssorallen** [comment]
Can you remove the whitespace and editor changes? It's tough to accept a pull request on an open source project that adds new whitespace and editor preferences. It'd be easier to potentially merge without those changes.

**Comment by danilvalov** [comment]
@ssorallen  Done

**Comment by dreamofdark** [comment]
@unclecheese 
Hello!
What about merge this pull request?

**Comment by unclecheese** [comment]
Thanks, everyone! Will tag as 2.1.0.

**Pull request merged**
